package lk.ijse.tccomputer.dao;

public enum DaoType {
    CUSTOMER,EMPLOYEE,EMPSALARYDETAIL,INCOME,ITEM,ORDERDETAIL,ORDERS,OUTCOME,REDUCESITEMDETAIL,REPAIR,SUPPLIER,SUPPLIES,SUPPLIESDETAIL,USER,QUERY
}
